#spring:
#  application:
#    name: CONSUMER-SERVICE
#  profiles:
#    active: dev
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 # nacos 注册中心
#
#dubbo:
#  registry:
#    address: nacos://127.0.0.1:8848 # nacos 注册中心
#  application:
#    name: CONSUMER-SERVICE
#  protocol:
#    name: dubbo
#    port: 5566
#
#server:
#  port: 8080