eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


server:
  port: 8918
spring:
  application:
    name: ZUUL-SERVER

management:
  endpoints:
    web:
      exposure:
        include: routes

