#spring:
#  application:
#    name: PRODUCER-SERVICE
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8083

#feign:
#  hystrix:
#    enabled: true